server:
  port: 8080
spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-service:
  greeting: "OLA"
  default-value: "Mundo"
  
  